# Pydantics helps define data shapes and automatically validates incoming data
from pydantic import BaseModel

# Used when creating a new user; doesn't unclude an ID because the server generates it
class UserCreate(BaseModel):
    name: str
    email: str

# Used when returning user data; inherits all fields from UseCreate and adds an ID
class User(UserCreate):
    id: int                 # Generated by the server